### ISSUE TITLE
deque<class>.push_back(class) isn't working 

### ISSUE THREAD

**Issue by ss-sebs-ss** [steelbrain/linter-ui-default#598]
In the last linter update, an error appeared : "no matching function for call to 'std::deque<acao>::push_back(<brace-enclosed initializer list>)", where "acao" is a class I'm using. I don't know if this error is a consequence from bad programming habits I have or any mistakes I made in the code (even though it compiles just right...), at least I hope this isn't the case. Anyway I thought it migh be worth a mention, just if it turns out to really be a bug.

**Comment by aminya** [comment]
This is not probably related to linter-ui-default. What linter provider are you using?

**Comment by ss-sebs-ss** [comment]
I'm using your linter for atom (I posted the error on the wrong github project, I'm sorry)

**Comment by aminya** [comment]
That's OK. My question was about the linter provider. The code seems like C++. While C++ linter provider are you using?

**Comment by ss-sebs-ss** [comment]
I'm using this linter: https://atom.io/packages/linter-gcc
